stages:
  preprocessing:
    cmd: venv\Scripts\python src/preprocessing.py
    deps:
      - src/data_ingestion.py
      - src/preprocessing.py
      - data/raw/churn_prediction_data.csv
    outs:
      - data/processed/test.csv
      - data/processed/train.csv

  training:
    matrix:
      model: [Logistic_Regression, Random_Forest, XGBoost]
    cmd: venv\Scripts\python src/train.py --model_name ${item.model}
    deps:
      - src/train.py
      - data/processed/train.csv
    outs:
      - artifacts/train/${item.model}_cm.png
      - artifacts/train/${item.model}_roc.png
      - models/${item.model}.skops

  evaluation:
    matrix:
      model: [Logistic_Regression, Random_Forest, XGBoost]
    cmd: venv\Scripts\python src/evaluate.py --model_name ${item.model}
    deps:
      - src/evaluate.py
      - models/${item.model}.skops
      - data/processed/test.csv
    outs:
      - artifacts/evaluation/${item.model}_feature.png
      - artifacts/evaluation/${item.model}_roc.png
      - data/generated/${item.model}_data.csv